// Global values

import 'package:flutter/material.dart';

String appName = 'MyNews';
String appVersion = '1.0';

String linkedinUrl =
    'https://www.linkedin.com/in/%D7%A2%D7%95%D7%9E%D7%A8-%D7%92%D7%9E%D7%9C%D7%99%D7%90%D7%9C-6a813a188';

String placeHolderAsset = 'Assets/images/placeHolder.jpg';
String loadingImageAsset = 'Assets/images/loading.jpg';
Map<String, int> pageIndexMap = {
  'Headlines': 0,
  'Topics': 1,
  'Saved': 2,
  'Search': 3,
  'Settings': 4
};

List<String> savedPrefsStr = [
  'showBottomSheet',
  'WelcomeDialog',
  'FavoritesDialog',
  'SettingsDialog',
  'NotSupportedCountry'
];
List<String> defaultsCategories = [
  'Business',
  'Entertainment',
  'Health',
  'Politics',
  'Science',
  'Sports',
  'Technology'
];

//String defaultSearchCountry = 'United States';
String searchCountryPrefsKey = 'lastLocation';
String fromDatePrefsKey = 'fromDate';
String toDatePrefsKey = 'toDate';
String searchDateModePrefsKey = 'SearchDateMode';
String dummyText =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse accumsan ligula at diam ultricies ornare. Ut at finibus augue. Ut posuere magna quis enim consectetur ornare. Donec ac sem turpis. In condimentum neque et odio commodo, in scelerisque mi pellentesque. Mauris facilisis a sapien ac consequat. Aenean congue tempor porttitor. Integer aliquet tincidunt neque vel dignissim. Integer iaculis aliquam ligula vitae tristique. Aliquam eget sollicitudin ante. Aliquam a tortor diam. Vivamus vel massa enim. Morbi volutpat est a nisl tincidunt, eu tempus augue semper. Donec a metus eget ipsum rhoncus bibendum sed at erat. Mauris eu pellentesque metus. Nunc ac dignissim magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dignissim aliquam nibh, blandit efficitur ipsum cursus sed. Vestibulum tristique vehicula ex quis posuere. Maecenas blandit magna at tincidunt hendrerit. Sed viverra, purus ac eleifend ultricies, velit augue venenatis enim, ac condimentum quam justo et tellus. Duis sit amet pulvinar massa. Duis ac erat nec nisi facilisis pellentesque suscipit nec urna. Proin euismod ultricies ex. Morbi euismod porta odio, eget iaculis lacus efficitur a. Suspendisse ac commodo urna. Mauris non augue tristique, scelerisque tellus quis, euismod sapien. Nam hendrerit lectus at urna pulvinar, a pellentesque justo mollis. Cras lobortis libero nulla. Donec cursus odio est, eget suscipit lorem semper et. Sed non accumsan ligula, ac accumsan sem. Morbi non orci rhoncus, cursus ligula eu, malesuada mi. Mauris fringilla rutrum sapien, et rhoncus nisi hendrerit vitae. Nulla sit amet purus nec justo porta congue. Proin eget lorem id libero vehicula commodo et fringilla est. Duis ac nibh porttitor, gravida nisi non, rutrum eros. Morbi nec diam a libero venenatis pretium id ac felis. Phasellus quis rutrum nulla. Maecenas aliquet tincidunt libero, et porta sem pretium nec. Phasellus vitae magna dui. Quisque scelerisque ex vitae metus venenatis, eu porta nulla dictum. Integer quis libero et justo elementum auctor id eget ante. Nunc vitae mattis justo, sed luctus eros. Nam in justo enim. In vitae blandit urna. Curabitur accumsan magna a urna suscipit, a fringilla ipsum bibendum. Proin sit amet odio sit amet odio eleifend molestie et sed magna. Integer facilisis ullamcorper nibh, quis sollicitudin lectus mattis eu. Vestibulum eu tristique leo, ut tincidunt felis. Suspendisse et mollis enim, lacinia ornare massa. Etiam nec euismod odio, in pretium nunc. Fusce blandit suscipit congue. Ut non mattis dolor, vel dignissim felis. Mauris vel dictum mauris. Vivamus id vulputate urna. Praesent ac eleifend odio. Morbi commodo tincidunt urna in pretium. Proin posuere commodo arcu non fermentum. Aliquam ut risus massa. Vivamus sit amet velit ac libero rutrum ullamcorper. Cras vel arcu a arcu rhoncus suscipit dictum nec tellus. Etiam rutrum velit in sodales dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam urna leo, condimentum ac cursus non, maximus in ante. Pellentesque ultricies neque nec diam sagittis, non sodales dolor aliquam. Etiam sagittis quis orci ut dignissim. Nullam maximus augue vel gravida fringilla. Suspendisse potenti. Nam finibus egestas elit, in lacinia dolor varius eget. Maecenas a posuere eros. Donec rhoncus nisl est, ac euismod mi rutrum ut. Nulla ornare vel ligula vel consequat. Suspendisse sit amet odio enim. In luctus consequat diam vel sollicitudin. Nam scelerisque scelerisque arcu a congue. Curabitur et dolor eu tortor viverra convallis sit amet tempus diam. Ut eget tortor vel sem consequat tempus non vitae massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut molestie ut elit vel ultrices. Mauris malesuada arcu ut porta luctus. Nunc dapibus convallis tortor non egestas. Cras ac urna sit amet ex tempor gravida in sed nulla. Nulla porttitor id arcu id laoreet. Mauris varius ex diam, sed posuere mi aliquet ut. Vestibulum suscipit, tortor in tincidunt vulputate, justo felis pretium neque, at tincidunt nisl orci vitae mi. Donec eu orci metus. Duis congue pharetra lacus. Nam vitae diam vulputate, pulvinar magna convallis, tempor massa. Aliquam porttitor ante lobortis odio condimentum, nec vulputate leo placerat. Nunc non magna quam. Proin ac elit nisl. Etiam lobortis elit ut iaculis semper. Maecenas aliquam pulvinar nibh ac egestas. Duis interdum ut risus sit amet iaculis. Ut vulputate justo at suscipit porta. Nam rhoncus dui nec elit rhoncus consectetur. Praesent aliquam justo id ante ullamcorper, eu lacinia ligula bibendum. Donec consequat mi sit amet ipsum ornare, eu malesuada felis mattis. In quis leo et massa fringilla pellentesque eu eu ante. Duis libero elit, consequat ut nibh in, fringilla gravida ex. Nam ac elit ultricies, mollis nibh sit amet, scelerisque purus. Vestibulum pretium imperdiet lobortis. Nullam iaculis risus vitae magna efficitur, et posuere lacus lacinia. Suspendisse turpis ipsum, pretium sit amet tempus ac, ultrices at purus. Phasellus rutrum eu nunc a tristique. Phasellus elit tellus, pulvinar eget elit sit amet, faucibus tristique tellus. Proin sagittis consectetur accumsan. Donec pulvinar metus at nibh placerat aliquam. Maecenas auctor pulvinar volutpat. Nam ut purus lectus. Vivamus quis tincidunt magna. Donec tempor eleifend neque, nec varius tortor dapibus eget. Mauris dignissim vitae risus eget venenatis.';

List<String> apiCountries = [
  'AE',
  'AR',
  'AT',
  'AU',
  'BE',
  'BG',
  'BR',
  'CA',
  'CH',
  'CN',
  'CO',
  'CU',
  'CZ',
  'DE',
  'EG',
  'FR',
  'GB',
  'GR',
  'HK',
  'HU',
  'ID',
  'IE',
  'IL',
  'IN',
  'IT',
  'JP',
  'KR',
  'LT',
  'LV',
  'MA',
  'MX',
  'MY',
  'NG',
  'NL',
  'NO',
  'NZ',
  'PH',
  'PL',
  'PT',
  'RO',
  'RS',
  'RU',
  'SA',
  'SE',
  'SG',
  'SI',
  'SK',
  'TH',
  'TR',
  'TW',
  'UA',
  'US',
  'VE',
  'ZA'
];

Map<String, String> countriesMap = {
  'Afghanistan': 'AF',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'American Samoa': 'AS',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Anguilla': 'AI',
  'Antarctica': 'AQ',
  'Antigua and Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Aruba': 'AW',
  'Australia': 'AU',
  'Austria': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bermuda': 'BM',
  'Bhutan': 'BT',
  'Bolivia, Plurinational State of': 'BO',
  'Bonaire, Sint Eustatius and Saba': 'BQ',
  'Bosnia and Herzegovina': 'BA',
  'Botswana': 'BW',
  'Bouvet Island': 'BV',
  'Brazil': 'BR',
  'British Indian Ocean Territory': 'IO',
  'Brunei Darussalam': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Cape Verde': 'CV',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  'China': 'CN',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo': 'CG',
  'Congo, the Democratic Republic of the': 'CD',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  'Country name': 'Code',
  'Croatia': 'HR',
  'Cuba': 'CU',
  'Curaçao': 'CW',
  'Cyprus': 'CY',
  'Czech Republic': 'CZ',
  "Côte d'Ivoire": 'CI',
  'Denmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Ecuador': 'EC',
  'Egypt': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Ethiopia': 'ET',
  'Falkland Islands (Malvinas)': 'FK',
  'Faroe Islands': 'FO',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'France': 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  'Gabon': 'GA',
  'Gambia': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greece': 'GR',
  'Greenland': 'GL',
  'Grenada': 'GD',
  'Guadeloupe': 'GP',
  'Guam': 'GU',
  'Guatemala': 'GT',
  'Guernsey': 'GG',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Heard Island and McDonald Islands': 'HM',
  'Holy See (Vatican City State)': 'VA',
  'Honduras': 'HN',
  'Hong Kong': 'HK',
  'Hungary': 'HU',
  'ISO 3166-2:GB': '(.uk)',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran, Islamic Republic of': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Isle of Man': 'IM',
  'Israel': 'IL',
  'Italy': 'IT',
  'Jamaica': 'JM',
  'Japan': 'JP',
  'Jersey': 'JE',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  "Korea, Democratic People's Republic of": 'KP',
  'Korea, Republic of': 'KR',
  'Kuwait': 'KW',
  'Kyrgyzstan': 'KG',
  "Lao People's Democratic Republic": 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Macao': 'MO',
  'Macedonia, the former Yugoslav Republic of': 'MK',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Martinique': 'MQ',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mayotte': 'YT',
  'Mexico': 'MX',
  'Micronesia, Federated States of': 'FM',
  'Moldova, Republic of': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Montserrat': 'MS',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Myanmar': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'Niue': 'NU',
  'Norfolk Island': 'NF',
  'Northern Mariana Islands': 'MP',
  'Norway': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Palestine, State of': 'PS',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Philippines': 'PH',
  'Pitcairn': 'PN',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Puerto Rico': 'PR',
  'Qatar': 'QA',
  'Romania': 'RO',
  'Russian Federation': 'RU',
  'Rwanda': 'RW',
  'Réunion': 'RE',
  'Saint Barthélemy': 'BL',
  'Saint Helena, Ascension and Tristan da Cunha': 'SH',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Martin (French part)': 'MF',
  'Saint Pierre and Miquelon': 'PM',
  'Saint Vincent and the Grenadines': 'VC',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Sint Maarten (Dutch part)': 'SX',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Georgia and the South Sandwich Islands': 'GS',
  'South Sudan': 'SS',
  'Spain': 'ES',
  'Sri Lanka': 'LK',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Svalbard and Jan Mayen': 'SJ',
  'Swaziland': 'SZ',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syrian Arab Republic': 'SY',
  'Taiwan, Province of China': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania, United Republic of': 'TZ',
  'Thailand': 'TH',
  'Timor-Leste': 'TL',
  'Togo': 'TG',
  'Tokelau': 'TK',
  'Tonga': 'TO',
  'Trinidad and Tobago': 'TT',
  'Tunisia': 'TN',
  'Turkey': 'TR',
  'Turkmenistan': 'TM',
  'Turks and Caicos Islands': 'TC',
  'Tuvalu': 'TV',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'United States Minor Outlying Islands': 'UM',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Venezuela, Bolivarian Republic of': 'VE',
  'Viet Nam': 'VN',
  'Virgin Islands, British': 'VG',
  'Virgin Islands, U.S.': 'VI',
  'Wallis and Futuna': 'WF',
  'Western Sahara': 'EH',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
  'Åland Islands': 'AX'
};

// const accent colors list
List<ColorSwatch> accentColors = const <ColorSwatch>[
  Colors.redAccent,
  Colors.pinkAccent,
  Colors.purpleAccent,
  Colors.deepPurpleAccent,
  Colors.indigoAccent,
  Colors.blueAccent,
  Colors.lightBlueAccent,
  Colors.cyanAccent,
  Colors.tealAccent,
  Colors.greenAccent,
  Colors.lightGreenAccent,
  Colors.limeAccent,
  Colors.yellowAccent,
  Colors.amberAccent,
  Colors.orangeAccent,
  Colors.deepOrangeAccent,
];

int lightAccentColorIndex = 5;
int darkAccentColorIndex = 8;
